using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace Sanguine_Forest
{
    /// <summary>
    /// Particle generated by particle system
    /// </summary>
    internal class Particle : GameObject
    {
        public Particle(Vector2 position, float rotation) : base(position, rotation) { }
    }
}
